Modal
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #12
Opened 2023-11-12 20:36 UTC by iKopturevskiy

2023-11-12 20:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 20:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 13:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 15:30 UTC, GSemikozov requested changes

2023-11-13 15:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
0

2023-11-13 15:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
0

2023-11-13 15:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    transform: translate(-50%, -50%);
лишнее

2023-11-13 16:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-13 16:40 UTC, iKopturevskiy commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
Готово

2023-11-13 16:40 UTC, iKopturevskiy commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
Готово

2023-11-13 16:40 UTC, iKopturevskiy commented on 05-lection3/02-modal/modal.css
> +    transform: translate(-50%, -50%);
Готово

2023-11-13 16:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 16:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 16:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 17:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 17:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 22:30 UTC, GSemikozov approved these changes

2023-11-13 22:30 UTC, merged