Аватар
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #16
Opened 2023-11-22 13:39 UTC by iKopturevskiy

2023-11-22 13:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-23 21:15 UTC, GSemikozov requested changes

2023-11-23 21:15 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    max-width: 200px;
просто width

2023-11-23 21:15 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    max-height: 200px;
height

2023-11-23 21:15 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
если вставить квадратную картинку, нормально отрисуется?

2023-11-25 08:31 UTC, iKopturevskiy commented on 06-lection4/01-avatar/avatar.css
> +    max-width: 200px;
Готово

2023-11-25 08:31 UTC, iKopturevskiy commented on 06-lection4/01-avatar/avatar.css
> +    max-height: 200px;
Готово

2023-11-25 08:32 UTC, iKopturevskiy commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
Нет) Теперь border-radius скругляет саму картинку, а не div

2023-11-25 20:54 UTC, GSemikozov requested changes
конфликт

2023-11-28 21:40 UTC, GSemikozov approved these changes

2023-11-28 21:40 UTC, merged