srcset
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #18
Opened 2023-11-22 15:56 UTC by iKopturevskiy

2023-11-22 15:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-23 21:17 UTC, GSemikozov requested changes

2023-11-23 21:17 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +                        public/forest_768.jpg"
`public/forest_768.jpg 2x`

2023-11-24 12:12 UTC, iKopturevskiy commented on 06-lection4/03-srcset/index.html
> +                        public/forest_768.jpg"
Исправил

2023-11-24 16:02 UTC, GSemikozov approved these changes

2023-11-24 16:02 UTC, merged