Задания с логотипом
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #20
Opened 2023-11-23 19:00 UTC by iKopturevskiy

2023-11-23 19:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-23 21:18 UTC, GSemikozov requested changes

2023-11-23 21:18 UTC, GSemikozov commented on index.html
> +                        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" >
не 3 отдельных элемента, а 1 общий - те у нас должна быть одна иконка)

2023-11-24 12:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-24 12:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-24 16:24 UTC, iKopturevskiy commented on index.html
> +                        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" >
Готово)

2023-11-24 16:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 09:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 09:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 09:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-25 20:53 UTC, GSemikozov approved these changes

2023-11-25 20:53 UTC, merged