burger-menu + стили container__title
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #25
Opened 2023-11-30 16:48 UTC by iKopturevskiy

2023-11-30 16:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-30 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-02 20:04 UTC, GSemikozov requested changes

2023-12-02 20:04 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-close {
.burger-menu__close

2023-12-02 20:04 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.preview_burger {
.burger-menu_preview

2023-12-03 07:32 UTC, iKopturevskiy commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-close {
Готово

2023-12-03 07:33 UTC, iKopturevskiy commented on 09-lection7/01-burger-menu/burger-menu.css
> +.preview_burger {
Исправил

2023-12-03 07:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-03 07:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 07:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 07:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 08:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 08:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 08:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 08:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-03 14:18 UTC, GSemikozov approved these changes

2023-12-03 14:18 UTC, merged