Задача про кнопки.
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #5
Opened 2023-11-05 20:31 UTC by iKopturevskiy

Я не понял как должны изменяться кнопки при нажатии. Сделал затухание как когда они не активны

2023-11-05 20:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-06 09:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-06 09:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-06 15:58 UTC, GSemikozov requested changes

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
ни в коем случае) наоборот - именно файлы компонентов импортируем в main)

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину не фиксируем

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    flex-shrink: 0;
лишнее

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    flex-shrink: 0;
не хватает паддингов

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
модификаторы пишем через `_`

2023-11-06 15:58 UTC, GSemikozov commented on assets/css/main.css
> +    --none: var(--none);
что-то странное) удалим

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: var(--none);
`border: 1px solid var(--primary);`?

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary-hover:hover {
.button_primary:hover

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: var(--none);
см выше

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 2px solid var(--grey-3);
1

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__disabled-05:disabled {
disabled для всех общий и записывается так: `.button:disabled`

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__cursor {
лишнее, удалим

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                        button
здесь будет только 2 класса: `button button_primary`

2023-11-06 15:58 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                        button
и ниже по аналогии

2023-11-06 18:30 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
Убрано.

2023-11-06 18:34 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    width: 189px;
Убрал

2023-11-06 18:44 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    flex-shrink: 0;
Так длина текста же разная и, если делать через паддинги, все кнопки будут разной ширины.

2023-11-06 18:46 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +.button__primary {
Исправил

2023-11-06 18:48 UTC, iKopturevskiy commented on assets/css/main.css
> +    --none: var(--none);
Удалил

2023-11-06 18:51 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    border: var(--none);
Исправил

2023-11-06 18:53 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +.button__primary-hover:hover {
Исправил

2023-11-06 18:53 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    border: var(--none);
Исправил

2023-11-06 18:58 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    border: 2px solid var(--grey-3);
Модификатор через одно _? Исправил

2023-11-06 19:00 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +.button__disabled-05:disabled {
Но там же у белой кнопки opacity: 0.3, а у остальных 0.5. По крайней мере так в фигме.

2023-11-06 19:03 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +.button__cursor {
Удалил

2023-11-06 19:09 UTC, iKopturevskiy commented on 03-lection1/01-button/index.html
> +                        button
Мне мешает разное opacity у кнопок, чтобы я мог убрать прям везде модификации и оставить по два класса. Получается мне надо везде принять opacity: 0.5?

2023-11-06 21:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    flex-shrink: 0;
именно так, и это правильно (у нас нет задачи сделать ширину всех кнопок одинаковой)

2023-11-06 21:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 2px solid var(--grey-3);
неа, ширина линии бордера - 1px)

2023-11-06 21:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__disabled-05:disabled {
договаривались упростить этот момент. Но можно отедльно для alternate добавить еще `.button_alternate:disabled { opacity: 0.3; }`

2023-11-06 21:07 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                        button
Получается мне надо везде принять opacity: 0.5? -> да, это было бы вполне ок

2023-11-07 18:37 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    border: 2px solid var(--grey-3);
Готово

2023-11-07 18:39 UTC, iKopturevskiy commented on 03-lection1/01-button/index.html
> +                        button
Выполнил

2023-11-07 18:40 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +.button__disabled-05:disabled {
Удалил

2023-11-07 18:43 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    flex-shrink: 0;
Исправил

2023-11-08 07:18 UTC, GSemikozov requested changes

2023-11-08 07:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 50px;
height: 48px

2023-11-08 07:18 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                        button_active-05
button_active-05 - и вот такие лишние классы надо удалить)

2023-11-09 18:05 UTC, iKopturevskiy commented on 03-lection1/01-button/index.html
> +                        button_active-05
Сделал

2023-11-09 18:06 UTC, iKopturevskiy commented on 03-lection1/01-button/button.css
> +    padding: 15px 50px;
Сделал

2023-11-10 09:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 13:56 UTC, GSemikozov approved these changes

2023-11-12 13:56 UTC, merged