Histogram
js-tasks-ru/htmlcss-20231027_ilya-kopturevskiy pull request #8
Opened 2023-11-10 13:43 UTC by iKopturevskiy

2023-11-10 13:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 14:04 UTC, GSemikozov requested changes

2023-11-12 14:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0 24px;
`16 24 24`

2023-11-12 14:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-around;
лишнее

2023-11-12 14:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
50

2023-11-12 14:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: baseline;
flex-end

2023-11-12 14:04 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <p>
`p` надо удалить

2023-11-12 20:14 UTC, iKopturevskiy commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0 24px;
Готово

2023-11-12 20:16 UTC, iKopturevskiy commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
Исправил

2023-11-12 20:17 UTC, iKopturevskiy commented on 04-lection2/01-histogram/index.html
> +                    <p>
Готово

2023-11-12 20:19 UTC, iKopturevskiy commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-around;
Удалил

2023-11-12 20:25 UTC, iKopturevskiy commented on 04-lection2/01-histogram/histogram.css
> +    align-items: baseline;
Готово

2023-11-13 15:27 UTC, GSemikozov approved these changes

2023-11-13 15:27 UTC, merged